/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vuhoang/tem_hum_sensor/src/temp_hum/srv/AddTwoInts.srv
 *
 */


#ifndef TEMP_HUM_MESSAGE_ADDTWOINTS_H
#define TEMP_HUM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <temp_hum/AddTwoIntsRequest.h>
#include <temp_hum/AddTwoIntsResponse.h>


namespace temp_hum
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace temp_hum


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::temp_hum::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::temp_hum::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::temp_hum::AddTwoInts > {
  static const char* value()
  {
    return "temp_hum/AddTwoInts";
  }

  static const char* value(const ::temp_hum::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::temp_hum::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::temp_hum::AddTwoInts > 
template<>
struct MD5Sum< ::temp_hum::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::temp_hum::AddTwoInts >::value();
  }
  static const char* value(const ::temp_hum::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::temp_hum::AddTwoIntsRequest> should match 
// service_traits::DataType< ::temp_hum::AddTwoInts > 
template<>
struct DataType< ::temp_hum::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::temp_hum::AddTwoInts >::value();
  }
  static const char* value(const ::temp_hum::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::temp_hum::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::temp_hum::AddTwoInts > 
template<>
struct MD5Sum< ::temp_hum::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::temp_hum::AddTwoInts >::value();
  }
  static const char* value(const ::temp_hum::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::temp_hum::AddTwoIntsResponse> should match 
// service_traits::DataType< ::temp_hum::AddTwoInts > 
template<>
struct DataType< ::temp_hum::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::temp_hum::AddTwoInts >::value();
  }
  static const char* value(const ::temp_hum::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEMP_HUM_MESSAGE_ADDTWOINTS_H
